---

- name: Check if Node is installed
  ansible.builtin.command: node -v
  register: nodejs_check
  ignore_errors: true
  
- name: Add NodeSource GPG key
  ansible.builtin.apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present
  when: nodejs_check.failed  

- name: Add NodeSource repository
  become: true
  apt_repository:
    repo: deb https://deb.nodesource.com/node_20.x {{ ansible_distribution_release }} main
    state: present
    update_cache: yes
  when: nodejs_check.failed  

- name: Install Node.js
  become: true
  apt:
    name: nodejs
    state: present
  when: nodejs_check.failed   



